#!/bin/sh

if tty -s
then
        echo "Run 'help' for help, or 'exit' to leave.  Available commands:"
        echo
else
        echo "Run 'help' for help.  Available commands:"
        echo
fi

cd "$(dirname "$0")"

for cmd in *
do
        case "$cmd" in
        help) ;;
        *) [ -f "$cmd" ] && [ -x "$cmd" ] && echo -n "$cmd - " && head -2 $cmd|tail -1|cut -c 2- ;;
        esac
done
